### ISSUE TITLE
Anti AFK hotkey documentation confusion

### ISSUE THREAD

**Issue by carloverso** [lemasato/POE-AHK-Utilities#2]
Having no experience with AHK it's pretty confusing to set up your key. In the documentation, it's suggested to use a flask key? "1-5", but assigned as "a". Do you just change to a number, or AHK wants special syntax?

How do you know if the script is working rather than just monitoring if you are going afk?

**Comment by lemasato** [comment]
That's an oversight. I forgot to set it back to "1" after testings.  
I'm personally using 12345 as my skills and azert as flasks.  
So simply change "a" to "1" and that'll work.  

No way to really see if it "works" (aside editing the timer), except looking at your flask charges.

**Comment by carloverso** [comment]
I'm not sure how hard is it, but perhaps you can change the tray icon if it's active? Maybe if active it changes to green? Otherwise, thanks for the clarification!

**Comment by lemasato** [comment]
That's currently the case. Clicking on the tray icon and "Pause" will make it appear more grayish. Though I guess it's not very visible and could use some tweaks.

**Comment by carloverso** [comment]
So clicking default "1" will turn it on permanently, until you close the script? If 1 is not a toggle key, maybe you can reflect that in the docs that you can't disable with the same key, which is perfectly good.

**Comment by lemasato** [comment]
It's not a toggle key. "KEY_TO_PRESS" refers to the key that will be pressed every once in a while.  
All you've got to do is run the script and that's it, no additional setup required.
